version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - database_data:/var/lib/postgresql/database_test/

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  database_data:
